package provider

import (
	"context"
	"crypto/tls"
	"errors"
	"net/http"
	"os"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/provider"
	"github.com/hashicorp/terraform-plugin-framework/provider/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/humanitec/humanitec-go-autogen"
	"sigs.k8s.io/yaml"
)

// Ensure HumanitecProvider satisfies various provider interfaces.
var _ provider.Provider = &HumanitecProvider{}

// HumanitecProvider defines the provider implementation.
type HumanitecProvider struct {
	// version is set to the provider version on release, "dev" when the
	// provider is built and ran locally, and "test" when running acceptance
	// testing.
	version string
}

// HumanitecProviderModel describes the provider data model.
type HumanitecProviderModel struct {
	APIPrefix types.String `tfsdk:"api_prefix"`
	Host      types.String `tfsdk:"host"`
	OrgID     types.String `tfsdk:"org_id"`
	Token     types.String `tfsdk:"token"`
	Config    types.String `tfsdk:"config"`

	DisableSSLCertificateVerification types.Bool `tfsdk:"disable_ssl_certificate_verification"`
}

const (
	HUM_CLIENT_ERR   = "Humanitec client error"
	HUM_API_ERR      = "Humanitec API error"
	HUM_PROVIDER_ERR = "Provider error"
	HUM_INPUT_ERR    = "Input error"
)

func (p *HumanitecProvider) Metadata(ctx context.Context, req provider.MetadataRequest, resp *provider.MetadataResponse) {
	resp.TypeName = "humanitec"
	resp.Version = p.version
}

func (p *HumanitecProvider) Schema(ctx context.Context, req provider.SchemaRequest, resp *provider.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Terraform Provider for [Humanitec](https://humanitec.com/).",

		Attributes: map[string]schema.Attribute{
			"api_prefix": schema.StringAttribute{
				MarkdownDescription: "Humanitec API prefix (or using the `HUMANITEC_API_PREFIX` environment variable)",
				Optional:            true,
			},
			"host": schema.StringAttribute{
				MarkdownDescription: "Humanitec API host (or using the `HUMANITEC_HOST` environment variable)",
				Optional:            true,
				DeprecationMessage:  "This attribute is deprecated in favor of api_prefix (`HUMANITEC_API_PREFIX` environment variable).",
			},
			"org_id": schema.StringAttribute{
				MarkdownDescription: "Humanitec Organization ID (or using the `HUMANITEC_ORG` environment variable)",
				Optional:            true,
			},
			"token": schema.StringAttribute{
				MarkdownDescription: "Humanitec Token (or using the `HUMANITEC_TOKEN` environment variable)",
				Optional:            true,
				Sensitive:           true,
			},
			"disable_ssl_certificate_verification": schema.BoolAttribute{
				MarkdownDescription: "Disables SSL certificate verification",
				Optional:            true,
			},
			"config": schema.StringAttribute{
				MarkdownDescription: "Location of Humanitec configuration",
				Optional:            true,
			},
		},
	}
}

func (p *HumanitecProvider) Configure(ctx context.Context, req provider.ConfigureRequest, resp *provider.ConfigureResponse) {
	var data HumanitecProviderModel

	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)

	if resp.Diagnostics.HasError() {
		return
	}

	var c Config

	// Check for .humctl file generated by humctl command line tool
	configFilePath := data.Config.ValueString()
	if configFilePath == "" {
		homeDir, err := os.UserHomeDir()
		if err != nil {
			resp.Diagnostics.AddWarning(
				"Unable to determine home directory",
				"While configuring the provider, terraform was unable "+
					"to determine user's home directory to read config file.",
			)
			configFilePath = ""
		} else {
			configFilePath = homeDir + "/.humctl"
			if _, err := os.Stat(configFilePath); errors.Is(err, os.ErrNotExist) {
				configFilePath = ""
			}
		}

	} else if _, err := os.Stat(configFilePath); errors.Is(err, os.ErrNotExist) {
		resp.Diagnostics.AddError(
			"Unable to read config file",
			"Terraform was unable to read config file mentioned "+
				"in the config attribute.",
		)
		// Not returning early allows the logic to collect all errors.
		configFilePath = ""
	}

	if configFilePath != "" {
		file, err := os.ReadFile(configFilePath)
		if err != nil {
			resp.Diagnostics.AddError(
				"Unable to read config file",
				"Terraform was unable to read the yaml config file "+
					"in "+configFilePath,
			)
			// Not returning early allows the logic to collect all errors.
		}

		err = yaml.Unmarshal(file, &c)
		if err != nil {
			resp.Diagnostics.AddError(
				"Unable to parse yaml from config file",
				"Terraform was unable to parse yaml config  "+
					"file in "+configFilePath,
			)
			// Not returning early allows the logic to collect all errors.
		}
	}
	apiPrefix := c.ApiPrefix
	orgID := c.Org
	token := c.Token

	// Environment variables have precedence over config file, if found
	if os.Getenv("HUMANITEC_API_PREFIX") != "" {
		apiPrefix = os.Getenv("HUMANITEC_API_PREFIX")
	} else {
		if hostOld := os.Getenv("HUMANITEC_HOST"); hostOld != "" {
			apiPrefix = hostOld
			resp.Diagnostics.AddWarning(
				"Environment variable HUMANITEC_HOST has been deprecated",
				"Environment variable HUMANITEC_HOST has been deprecated "+
					"please use HUMANITEC_API_PREFIX instead to set your api prefix to the terraform driver.")
		} else {
			apiPrefix = humanitec.DefaultAPIHost
		}
	}

	if os.Getenv("HUMANITEC_ORG") != "" {
		orgID = os.Getenv("HUMANITEC_ORG")
	}

	if os.Getenv("HUMANITEC_TOKEN") != "" {
		token = os.Getenv("HUMANITEC_TOKEN")
	}

	// Check configuration data, which should take precedence over
	// environment variable data and config file, if found.
	if data.APIPrefix.ValueString() != "" {
		apiPrefix = data.APIPrefix.ValueString()
	} else if data.Host.ValueString() != "" {
		apiPrefix = data.Host.ValueString()
		resp.Diagnostics.AddWarning(
			"Attribute host has been deprecated",
			"Attribute hostT has been deprecated "+
				"please use api_prefix instead to set your api prefix to the terraform driver.")
	}

	if data.OrgID.ValueString() != "" {
		orgID = data.OrgID.ValueString()
	}

	if data.Token.ValueString() != "" {
		token = data.Token.ValueString()
	}

	if token == "" {
		resp.Diagnostics.AddError(
			"Missing API Token Configuration",
			"While configuring the provider, the API token was not found in "+
				"the HUMANITEC_TOKEN environment variable or provider "+
				"configuration block token attribute.",
		)
		// Not returning early allows the logic to collect all errors.
	}

	if orgID == "" {
		resp.Diagnostics.AddError(
			"Missing API Org ID Configuration",
			"While configuring the provider, the API token was not found in "+
				"the HUMANITEC_ORG environment variable or provider "+
				"configuration block org_id attribute.",
		)
		// Not returning early allows the logic to collect all errors.
	}

	var doer *http.Client
	if data.DisableSSLCertificateVerification.ValueBool() {
		tr := &http.Transport{
			TLSClientConfig: &tls.Config{InsecureSkipVerify: true},
		}
		doer = &http.Client{Transport: tr}
	} else {
		doer = &http.Client{}
	}

	client, err := NewHumanitecClient(apiPrefix, token, p.version, doer)
	if err != nil {
		resp.Diagnostics.AddError("Unable to create Humanitec client", err.Error())
	}

	if resp.Diagnostics.HasError() {
		return
	}

	sourcedata := &HumanitecData{
		Client: client,
		OrgID:  orgID,
	}

	resp.DataSourceData = sourcedata
	resp.ResourceData = sourcedata
}

func (p *HumanitecProvider) Resources(ctx context.Context) []func() resource.Resource {
	return []func() resource.Resource{
		NewResourceAccountResource,
		NewResourceAgent,
		NewResourceApplication,
		NewResourceApplicationUser,
		NewResourceArtefactVersion,
		NewResourceDefinitionCriteriaResource,
		NewResourceDefinitionResource,
		NewResourceEnvironmentType,
		NewResourceEnvironmentTypeUser,
		NewResourceKey,
		NewResourcePipeline,
		NewResourcePipelineCriteria,
		NewResourceRegistry,
		NewResourceResourceDriver,
		NewResourceRule,
		NewResourceSecretStore,
		NewResourceServiceUserToken,
		NewResourceValue,
		NewResourceUser,
		NewResourceWebhook,
		NewResourceWorkloadProfileChartVersion,
		NewResourceWorkloadProfile,
	}
}

func (p *HumanitecProvider) DataSources(ctx context.Context) []func() datasource.DataSource {
	return []func() datasource.DataSource{
		NewSourceIPRangesDataSource,
		NewUsersDataSource,
	}
}

func New(version string) func() provider.Provider {
	return func() provider.Provider {
		return &HumanitecProvider{
			version: version,
		}
	}
}
