name: Terraform Provider Tests

on: [push]

jobs:
  acceptance:
    name: Acceptance Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
          cache: true
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.5.*"
          terraform_wrapper: false
      - run: make testacc
        env:
          HUMANITEC_ORG: ${{ secrets.HUMANITEC_ORG_ID }} # Reusing env variable on GitHub Actions
          HUMANITEC_TOKEN: ${{ secrets.HUMANITEC_TOKEN }}
  unit:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
          cache: true
      - name: Tidy go.mod file
        run: go mod tidy
      - name: Generate docs
        run: go generate ./...
      - name: Check git diff is clean (all files generated should be committed)
        run: git diff --exit-code
      - name: Run tests
        run: go test -v -cover ./...
